dist: xenial
services: rabbitmq
language: python

matrix:
  include:
  - name: "3.6-unit"
    python: "3.6"
    env: LIMIT=500
    env: TEST=unit
  - name: "3.6-static_flow"
    python: "3.6"
    env: LIMIT=500
    env: TEST=static_flow
  - name: "3.6-dyn500"
    python: "3.6"
    env: LIMIT=500
    env: TEST=dynamic_flow
  - name: "3.5-dyn1000"
    python: "3.5"
    env: LIMIT=1000
    env: TEST=dynamic_flow
  - name: "3.6-dyn2000"
    python: "3.6"
    env: LIMIT=2000
    env: TEST=dynamic_flow
  - name: "3.7-dyn3000"
    python: "3.7"
    env: LIMIT=3000
    env: TEST=dynamic_flow


branches:
  only:
  - master
  - issue187

install:
- travis/flow_autoconfig.sh

script:
- cd ${HOME}/sr_insects/$TEST
- ./flow_setup.sh
- timeout 30m ./flow_limit.sh $LIMIT
- ./flow_check.sh
- ./flow_cleanup.sh

