dist: xenial
services: rabbitmq
language: python

matrix:
  include:
  - name: "3.5-500limit"
    python: "3.5"
    env: LIMIT=500
  - name: "3.5-1000limit"
    python: "3.5"
    env: LIMIT=1000
  - name: "3.6-2000limit"
    python: "3.6"
    env: LIMIT=2000
  - name: "3.7-3000limit"
    python: "3.7"
    env: LIMIT=3000


branches:
  only:
  - master

install:
- cd test
- ./flow_autoconfig.sh

script:
- ./flow_setup.sh
- timeout 30m ./flow_limit.sh $LIMIT
- ./flow_check.sh
- ./flow_cleanup.sh

