dist: xenial
services: rabbitmq
language: python

matrix:
  include:
  - name: "3.6-unit"
    python: "3.6"
    env: LIMIT=500
    env: TEST=unit
  - name: "3.6-static_flow"
    python: "3.6"
    env: LIMIT=500
    env: TEST=static_flow
# while in issue187 branch shorter is better. 
#  - name: "3.5-1000limit"
#    python: "3.5"
#    env: LIMIT=1000
#  - name: "3.6-2000limit"
#    python: "3.6"
#    env: LIMIT=2000
#  - name: "3.7-3000limit"
#    python: "3.7"
#    env: LIMIT=3000


branches:
  only:
  - master
  - issue187

install:
- travis/flow_autoconfig.sh

script:
- cd ${HOME}/sr_insects/$TEST
- ./flow_setup.sh
- timeout 30m ./flow_limit.sh $LIMIT
- ./flow_check.sh
- ./flow_cleanup.sh

