dist: xenial
services: rabbitmq
language: python

matrix:
  include:
  - name: "3.4-700limit"
    python: "3.4"
    env: LIMIT=700
  - name: "3.5-1000limit"
    python: "3.5"
    env: LIMIT=1000
  - name: "3.6-3000limit"
    python: "3.6"
    env: LIMIT=3000
  - name: "3.7-10000limit"
    python: "3.7"
    env: LIMIT=10000


branches:
  only:
  - master

install:
- cd test
- ./flow_autoconfig.sh

before_script:
- ./flow_setup.sh
- ./flow_limit.sh $LIMIT

script:
- ./flow_check.sh
- ./flow_cleanup.sh

cache:
   directories:
   - /home/travis/.cache/sarra/log
