dist: xenial
services: rabbitmq
language: python

matrix:
  include:
  - name: "3.4-100limit"
    python: "3.4"
    env: LIMIT=100
  - name: "3.5-1000limit"
    python: "3.5"
    env: LIMIT=1000
  - name: "3.6-3000limit"
    python: "3.6"
    env: LIMIT=3000
  - name: "3.7-7000limit"
    python: "3.7"
    env: LIMIT=7000


branches:
  only:
  - master

install:
- cd test
- ./flow_autoconfig.sh

script:
- ./flow_setup.sh
- timeout 45m ./flow_limit.sh $LIMIT
- ./flow_check.sh
- ./flow_cleanup.sh

cache: pip
